
name: needworkflow

on:
 workflow_dispatch:
env:
  worflowlevelvariable: srinu
jobs:
  need_jobpipline:
   runs-on: ubuntu-24.04
   steps:
    - run: echo "print first job"
    - run: echo "one or more job run based on this job $worflowlevelvariable"
  second_job:
   runs-on: ubuntu-24.04
   needs: 
   - need_jobpipline
   steps:
    - run: echo "rnn the second jon $worflowlevelvariable"
  thrid_job:
    runs-on: ubuntu-24.04
    needs:
     - need_jobpipline
     - second_job
    steps:
      - run: echo "print first and second based on thrid $worflowlevelvariable"
      
  
    
    
      
   
  
  
  

   
