name: bulid and output file

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Generate version
        id: version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "version=$VERSION" >> "$GITHUB_ENV"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Testing version"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying $version"
            
    
          
          
          
        
       
