name: secrets and vars
on:
 workflow_dispatch:
env:
  name = ${{ secrets.NAME }}
  branch = ${{ secrets.BRANCH }}
jobs:
  secrets:
     runs-on: ubuntu-22.04
     steps:
       - name: priting secrets
         run:
          echo "print secretres of devploment $name"
