name: secrets and vars

on:
  workflow_dispatch:

env:
  NAME: ${{ secrets.NAME }}
  BRANCH: ${{ secrets.BRANCH }}

jobs:
  secrets:
    runs-on: ubuntu-22.04

    steps:
      - name: printing secrets
        run: |
          echo "print secrets of deployment $NAME"
          echo "branch is $BRANCH"
